name: TencentCloudBase
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Tencent CloudBase1
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        with:
          secretId: ${{secrets.SECRETID}}
          secretKey: ${{secrets.SECRETKEY}}
          envId: ${{secrets.APPID}}
          staticSrcPath: ./
